site_name: Doorstop
site_description: Requirements management using version control.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/doorstop

theme: readthedocs

pages:
- Home: index.md
- About:
  - 'Release Notes': about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
