name: Execute tests
on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
      basepath:
        required: true
        type: string
      os:
        required: true
        type: string
      workpath:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    name: Python ${{ matrix.python-version }}

    defaults:
      run:
        working-directory: ${{ inputs.workpath }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ inputs.architecture }}

      - uses: Gr1N/setup-poetry@v7

      - name: Check system dependencies
        run: make doctor

      - uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install project dependencies
        run: make install

      - name: Run tests
        run: make test

      - name: Run checks
        run: make check

      - name: Run demo
        run: make demo
