name: Execute tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      workpath:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        python-version: [ '3.7', ]
    name: Python ${{ matrix.python-version }}

    defaults:
      run:
        working-directory: ${{ inputs.workpath }}

    steps:
    - name: Checkout
      run: |
        mkdir ${{ inputs.workpath }}
        git clone $${{ github.GITHUB_REPOSITORY }} ${{ inputs.workpath }} --depth 1
    # - uses: actions/checkout@v3
    #   with:
    #     path: ${{ inputs.workpath }}

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install poetry
      run: pip install poetry

    - name: Install graphviz Mac OS X
      run: brew install graphviz
      if: ${{ inputs.os == 'macos-latest' }}

    - name: Install graphviz Windows
      run: |
        echo ${env.GITHUB_WORKSPACE}
        choco install graphviz
      if: ${{ inputs.os == 'windows-latest' }}

    - name: Install graphviz Ubuntu
      run: sudo apt install graphviz
      if: ${{ inputs.os == 'ubuntu-latest' }}

    - name: doctor
      run: make doctor

    - name: Run test
      run: |
        make test
        git clean -f
        git checkout .

    - name: Run full CI
      run: make ci
