name: Execute tests

on:
  workflow_call:
  #   inputs:
  #     username:
  #       required: true
  #       type: string
  #   secrets:
  #     token:
  #       required: true

# jobs:
#   example_job:
#     name: Pass input and secrets to my-action
#     runs-on: ubuntu-latest
#     steps:
#       - uses: ./.github/workflows/my-action
#         with:
#           username: ${{ inputs.username }}
#           token: ${{ secrets.token }}
jobs:
  test:

    strategy:
      matrix:
        python-version: [ '3.7', '3.8' ]
    name: Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install poetry
      run: pip install poetry

    - name: Install graphviz
      run: brew install graphviz

    - name: doctor
      run: make doctor

    - name: Run test
      run: make test

    - name: Run full CI
      run: make ci
