name: Linux Test

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    uses: ./.github/workflows/execute-tests.yml
    with:
      basepath: '/home/runner/work'
      os: 'ubuntu-latest'
      workpath: '/home/runner/work/doorstop/doorstop'
