name: Mac OS X Test

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    uses: ./.github/workflows/execute-tests.yml
    with:
      os: 'macos-latest'
      workpath: '/Users/runner/work/doorstop/doorstop'
