name: Mac OS X Test

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on:
    - macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Activate python 3-1
      run: echo "$PATH" && which python && python version

    - name: Activate python 3-2
      run: echo "/usr/local/bin/python:$PATH" >> ~/.profile

    - name: Activate python 3-3
      run: echo "$PATH" && which python && python version

    - name: Install poetry
      run: pip3 install poetry

    - name: Install graphviz
      run: brew install graphviz

    - name: doctor
      run: make doctor

    - name: Run test
      run: make test

    - name: Run full CI
      run: make ci
