name: Linux Test

# Run on all pushes and PRs to 'develop'.
on:
  push:
  pull_request:
    branches: [ develop ]

# Run on all pushes and PRs to 'develop'.
jobs:
  test:
    uses: ./.github/workflows/execute-tests.yml
    with:
      basepath: '/home/runner/work'
      os: 'ubuntu-latest'
      workpath: '/home/runner/work/doorstop/doorstop'
