name: Mac OS X Test

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on:
    - macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Remove python 2
      run: sudo rm -fr /usr/bin/python

    - name: Activate python 3
      run: sudo ln -s /usr/local/bin/python3 /usr/bin/python

    - name: Install poetry
      run: pip3 install poetry

    - name: Install graphviz
      run: brew install graphviz

    - name: doctor
      run: make doctor

    - name: Run test
      run: make test

    - name: Run full CI
      run: make ci
